"use client";

import { useState, useEffect } from "react";
import { trpc } from "@/lib/trpc/client";
import { FileText, Sparkles, Loader2, Download, Activity, CheckCircle2, AlertTriangle, Building } from "lucide-react";
import { ChatOpenAI } from "@langchain/openai";

// Sprint health calculation from velocity and cycle time distribution
function computeSprintHealthScore(completed: number, committed: number, avgCycleTime: number): { score: number; label: string; color: string } {
    const completionRate = committed > 0 ? completed / committed : 0;
    // Weighted: 70% completion rate, 30% cycle time efficiency (< 5 days = healthy)
    const cycleScore = Math.max(0, 1 - (avgCycleTime - 2) / 10);
    const score = Math.round((completionRate * 70 + cycleScore * 30));

    if (score >= 85) return { score, label: "Healthy", color: "text-green-500" };
    if (score >= 60) return { score, label: "At Risk", color: "text-amber-500" };
    return { score, label: "Critical", color: "text-red-500" };
}

const MOCK_SPRINT_STATS = {
    committed: 42,
    completed: 38,
    avgCycleDays: 3.5,
    openIssues: 6,
    blockedIssues: 1,
};

export default function ReportsPage() {
    const [selectedProjectId, setSelectedProjectId] = useState<string>("");
    const [report, setReport] = useState<string | null>(null);
    const [isGenerating, setIsGenerating] = useState(false);

    // Fetch all PM Projects
    const { data: projects, isLoading: isProjectsLoading } = trpc.pmProjects.list.useQuery();

    useEffect(() => {
        if (projects && projects.length > 0 && (!selectedProjectId || !projects.find((p: any) => p.id === selectedProjectId))) {
            setSelectedProjectId(projects[0].id);
        } else if (projects?.length === 0) {
            setSelectedProjectId("");
        }
    }, [projects, selectedProjectId]);

    const health = computeSprintHealthScore(
        MOCK_SPRINT_STATS.completed,
        MOCK_SPRINT_STATS.committed,
        MOCK_SPRINT_STATS.avgCycleDays
    );

    async function generateReport() {
        if (!selectedProjectId) return;
        
        setIsGenerating(true);
        try {
            // Call the report generation API
            const response = await fetch("/api/pm/reports/generate", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ projectId: selectedProjectId, stats: MOCK_SPRINT_STATS }),
            });

            if (response.ok) {
                const data = await response.json();
                setReport(data.report);
            } else {
                // Fallback mock report
                setReport(generateMockReport());
            }
        } catch {
            setReport(generateMockReport());
        } finally {
            setIsGenerating(false);
        }
    }

    function generateMockReport() {
        return `# Sprint Weekly Report — ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}

## Executive Summary
The team completed **${MOCK_SPRINT_STATS.completed} of ${MOCK_SPRINT_STATS.committed} story points** this sprint, achieving a **${Math.round((MOCK_SPRINT_STATS.completed / MOCK_SPRINT_STATS.committed) * 100)}% completion rate**. Sprint health is rated **${health.label}** (${health.score}/100).

## Sprint Health Score: ${health.score}/100 — ${health.label}

| Metric | Value |
|---|---|
| Committed | ${MOCK_SPRINT_STATS.committed} pts |
| Completed | ${MOCK_SPRINT_STATS.completed} pts |
| Avg. Cycle Time | ${MOCK_SPRINT_STATS.avgCycleDays} days |
| Open Issues | ${MOCK_SPRINT_STATS.openIssues} |
| Blocked Issues | ${MOCK_SPRINT_STATS.blockedIssues} |

## Risks & Blockers
- **${MOCK_SPRINT_STATS.blockedIssues} issue** is currently blocked. Immediate attention required.
- ${MOCK_SPRINT_STATS.openIssues} issues remain open and are at risk of rolling over to next sprint.

## Recommendations
1. **Unblock FPM-7** — escalate dependency to remove the blocker before EOD.
2. **Reduce WIP** — consider limiting in-progress work to 3 issues per developer to reduce cycle time.
3. **Pre-plan next sprint** — with the current velocity trend, target **40 story points** for the next sprint.

---
*Generated by F.R.I.D.A.Y AI Reports Engine*`;
    }

    function downloadReport() {
        if (!report) return;
        const blob = new Blob([report], { type: "text/markdown" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `sprint-report-${new Date().toISOString().split("T")[0]}.md`;
        a.click();
        URL.revokeObjectURL(url);
    }

    return (
        <div className="h-full overflow-y-auto p-6 space-y-6 max-w-5xl mx-auto">
            <div className="flex items-start justify-between">
                <div>
                    <h2 className="text-2xl font-bold tracking-tight">Reports</h2>
                    <p className="text-muted-foreground">AI-generated sprint summaries and health diagnostics.</p>
                </div>
                <div className="flex items-center gap-4">
                    <div className="flex items-center gap-3 bg-card border border-border rounded-lg px-3 py-2 shadow-sm">
                        <Building size={16} className="text-muted-foreground" />
                        <select 
                            value={selectedProjectId}
                            onChange={(e) => setSelectedProjectId(e.target.value)}
                            className="bg-transparent border-none text-sm font-medium focus:ring-0 cursor-pointer outline-none w-48"
                            disabled={isProjectsLoading}
                        >
                            {isProjectsLoading ? (
                                <option>Loading projects...</option>
                            ) : projects?.length ? (
                                projects.map((p: any) => (
                                    <option key={p.id} value={p.id}>{p.name}</option>
                                ))
                            ) : (
                                <option value="">No projects found</option>
                            )}
                        </select>
                    </div>
                    {report && (
                        <button
                            onClick={downloadReport}
                            className="flex items-center gap-2 px-4 py-2 border border-border rounded-md text-sm hover:bg-muted"
                        >
                            <Download size={16} /> Export Markdown
                        </button>
                    )}
                </div>
            </div>

            {/* Sprint Health Score Card */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="bg-card border border-border rounded-xl p-5 col-span-1 md:col-span-1 flex flex-col items-center justify-center text-center">
                    <div className="text-xs text-muted-foreground mb-2 flex items-center gap-1">
                        <Activity size={12} /> Sprint Health Score
                    </div>
                    <div className={`text-5xl font-black ${health.color}`}>{health.score}</div>
                    <div className={`text-sm font-semibold mt-1 ${health.color}`}>{health.label}</div>
                    <div className="text-xs text-muted-foreground mt-2">{MOCK_SPRINT_STATS.completed}/{MOCK_SPRINT_STATS.committed} pts completed</div>
                </div>

                <div className="col-span-1 md:col-span-2 grid grid-cols-2 gap-3">
                    {[
                        { label: "Committed", value: `${MOCK_SPRINT_STATS.committed} pts`, icon: CheckCircle2, color: "text-blue-500" },
                        { label: "Completed", value: `${MOCK_SPRINT_STATS.completed} pts`, icon: CheckCircle2, color: "text-green-500" },
                        { label: "Avg Cycle Time", value: `${MOCK_SPRINT_STATS.avgCycleDays}d`, icon: Activity, color: "text-purple-500" },
                        { label: "Blocked Issues", value: MOCK_SPRINT_STATS.blockedIssues, icon: AlertTriangle, color: "text-red-500" },
                    ].map(({ label, value, icon: Icon, color }) => (
                        <div key={label} className="bg-card border border-border rounded-lg p-4">
                            <div className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                                <Icon size={12} className={color} /> {label}
                            </div>
                            <div className="text-xl font-bold">{value}</div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Report Gen */}
            {!report ? (
                <div className="bg-card border border-border rounded-xl p-10 text-center flex flex-col items-center gap-4">
                    <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center">
                        <FileText className="w-8 h-8 text-primary" />
                    </div>
                    <div>
                        <h3 className="font-semibold text-lg">Generate Weekly Report</h3>
                        <p className="text-sm text-muted-foreground max-w-sm mt-1">
                            F.R.I.D.A.Y will analyze sprint metrics, risks, and velocity trends to produce an executive-grade report.
                        </p>
                    </div>
                    <button
                        onClick={generateReport}
                        disabled={isGenerating}
                        className="flex items-center gap-2 px-6 py-2.5 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 disabled:opacity-50 text-sm font-medium"
                    >
                        {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                        {isGenerating ? "Analyzing Sprint..." : "Generate AI Report"}
                    </button>
                </div>
            ) : (
                <div className="bg-card border border-border rounded-xl p-6">
                    <pre className="whitespace-pre-wrap text-sm leading-relaxed font-mono text-foreground/90">{report}</pre>
                    <div className="mt-6 pt-4 border-t border-border flex gap-3">
                        <button
                            onClick={() => { setReport(null); }}
                            className="px-4 py-2 text-sm border rounded-md hover:bg-muted"
                        >
                            Regenerate
                        </button>
                        <button
                            onClick={downloadReport}
                            className="flex items-center gap-2 px-4 py-2 text-sm bg-primary text-primary-foreground rounded-md hover:bg-primary/90"
                        >
                            <Download size={14} /> Download
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
}
